# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c99130a1fbd8a2f1fc591331188a0d694eec8c06dc0d4420890ce8efc462e8139602ad7728d9e7132522e1de99abb2e8a70369c31d26f6fef33c14a7109e2c8

test:
  secret_key_base: b44c7b8b493d46a7077c9200a784d8048a54e8fdfd4f0b7791820b6d9febaea0a881f6af1e999d9e5432504df9d5bdb1d579c3a9f5b895b0c82fd14584ef10c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
